FROM node:22.12.0-alpine3.21

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 8000

CMD ["sh", "-c", "npm run prisma:deploy && npm run prisma:generate && npm run start:prod"]
